[2025-05-19T07:31:17.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-19T07:31:17.081+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.load_to_postgres manual__2025-05-19T07:28:22.740128+00:00 [queued]>
[2025-05-19T07:31:17.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.load_to_postgres manual__2025-05-19T07:28:22.740128+00:00 [queued]>
[2025-05-19T07:31:17.086+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-05-19T07:31:17.095+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-05-19 07:28:22.740128+00:00
[2025-05-19T07:31:17.108+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-19T07:31:17.102+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'load_to_postgres', 'manual__2025-05-19T07:28:22.740128+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_pipeline.py', '--cfg-path', '/tmp/tmp_whhhp1i']
[2025-05-19T07:31:17.111+0000] {standard_task_runner.py:64} INFO - Started process 256 to run task
[2025-05-19T07:31:17.112+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask load_to_postgres
[2025-05-19T07:31:17.169+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_price_pipeline.load_to_postgres manual__2025-05-19T07:28:22.740128+00:00 [running]> on host 286fd7c1dbed
[2025-05-19T07:31:17.486+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T07:28:22.740128+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T07:28:22.740128+00:00'
[2025-05-19T07:31:17.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-19T07:31:17.495+0000] {loading.py:35} INFO - Starting data loading from MYSQL table flight_prices_raw_transformed to PostgreSQL
[2025-05-19T07:31:21.450+0000] {loading.py:60} INFO - Loaded 57000 rows from MySQL flight_prices_raw_transformed to PostgreSQL
[2025-05-19T07:31:21.454+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-19T07:31:21.455+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/loading.py", line 75, in load_to_postgres
    kpi_df = kpis.get(kpi_name)
             ^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
[2025-05-19T07:31:21.487+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flight_price_pipeline, task_id=load_to_postgres, run_id=manual__2025-05-19T07:28:22.740128+00:00, execution_date=20250519T072822, start_date=20250519T073117, end_date=20250519T073121
[2025-05-19T07:31:21.502+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task load_to_postgres ('str' object has no attribute 'get'; 256)
[2025-05-19T07:31:21.563+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-19T07:31:21.621+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T07:31:21.623+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
